"""
AWS-specific stub configuration for dataclass_dsl.

Provides AWS_STUB_CONFIG for generating .pyi stub files that work
with wetwire-aws imports. The stub generator uses this to expand
star imports and re-export all service modules.
"""

from dataclass_dsl import StubConfig

# All names exported from wetwire_aws that should be available
# via `from . import *` in resource packages.
AWS_CORE_EXPORTS = [
    # Decorator
    "wetwire_aws",
    # Base classes
    "CloudFormationResource",
    "PropertyType",
    "Tag",
    # Policy helpers
    "PolicyStatement",
    "DenyStatement",
    "PolicyDocument",
    # Template and components
    "CloudFormationTemplate",
    "Parameter",
    "Output",
    "Mapping",
    "TemplateCondition",
    # Reference types from dataclass-dsl
    "Ref",
    "Attr",
    "RefList",
    "RefDict",
    # Reference helpers
    "ref",
    "get_att",
    "ARN",
    # Intrinsic functions (CF intrinsics)
    "RefIntrinsic",
    "GetAtt",
    "Sub",
    "Join",
    "Select",
    "Split",
    "If",
    "Equals",
    "And",
    "Or",
    "Not",
    "Base64",
    "GetAZs",
    "ImportValue",
    "FindInMap",
    "Transform",
    "Cidr",
    "Condition",
    # Parameter type constants
    "STRING",
    "NUMBER",
    "LIST_NUMBER",
    "COMMA_DELIMITED_LIST",
    "SSM_PARAMETER_STRING",
    "SSM_PARAMETER_STRING_LIST",
    "AVAILABILITY_ZONE",
    "LIST_AVAILABILITY_ZONE",
    "AMI_ID",
    "INSTANCE_ID",
    "KEY_PAIR",
    "SECURITY_GROUP_ID",
    "LIST_SECURITY_GROUP_ID",
    "SUBNET_ID",
    "LIST_SUBNET_ID",
    "VPC_ID",
    "VOLUME_ID",
    "HOSTED_ZONE_ID",
    # Pseudo-parameters
    "AWS_ACCOUNT_ID",
    "AWS_NOTIFICATION_ARNS",
    "AWS_NO_VALUE",
    "AWS_PARTITION",
    "AWS_REGION",
    "AWS_STACK_ID",
    "AWS_STACK_NAME",
    "AWS_URL_SUFFIX",
    # Condition operator constants
    "BOOL",
    "STRING_EQUALS",
    "STRING_NOT_EQUALS",
    "STRING_EQUALS_IGNORE_CASE",
    "STRING_NOT_EQUALS_IGNORE_CASE",
    "STRING_LIKE",
    "STRING_NOT_LIKE",
    "NUMERIC_EQUALS",
    "NUMERIC_NOT_EQUALS",
    "NUMERIC_LESS_THAN",
    "NUMERIC_LESS_THAN_EQUALS",
    "NUMERIC_GREATER_THAN",
    "NUMERIC_GREATER_THAN_EQUALS",
    "DATE_EQUALS",
    "DATE_NOT_EQUALS",
    "DATE_LESS_THAN",
    "DATE_LESS_THAN_EQUALS",
    "DATE_GREATER_THAN",
    "DATE_GREATER_THAN_EQUALS",
    "IP_ADDRESS",
    "NOT_IP_ADDRESS",
    "ARN_EQUALS",
    "ARN_NOT_EQUALS",
    "ARN_LIKE",
    "ARN_NOT_LIKE",
    "NULL",
    # Loader
    "setup_resources",
]

# Service modules dynamically injected from wetwire_aws.resources
# These are added to expand_star_imports to ensure stubs include them
AWS_SERVICE_MODULES = [
    "acmpca",
    "amplify",
    "amplifyuibuilder",
    "apigateway",
    "apigatewayv2",
    "appconfig",
    "appflow",
    "appintegrations",
    "applicationautoscaling",
    "applicationinsights",
    "applicationsignals",
    "apprunner",
    "appstream",
    "appsync",
    "aps",
    "athena",
    "auditmanager",
    "autoscaling",
    "autoscalingplans",
    "b2bi",
    "backup",
    "batch",
    "bedrock",
    "billingconductor",
    "budgets",
    "cassandra",
    "ce",
    "certificatemanager",
    "chatbot",
    "cleanrooms",
    "cleanroomsml",
    "cloud9",
    "cloudformation",
    "cloudfront",
    "cloudtrail",
    "cloudwatch",
    "codeartifact",
    "codebuild",
    "codecommit",
    "codeconnections",
    "codedeploy",
    "codeguruprofiler",
    "codegurureviewer",
    "codepipeline",
    "codestar",
    "codestarconnections",
    "codestarnotifications",
    "cognito",
    "comprehend",
    "config",
    "connect",
    "controltower",
    "cur",
    "customerprofiles",
    "databrew",
    "datapipeline",
    "datasync",
    "datazone",
    "dax",
    "deadline",
    "detective",
    "devopsguru",
    "directoryservice",
    "dlm",
    "dms",
    "docdb",
    "docdbelastic",
    "dynamodb",
    "ec2",
    "ecr",
    "ecs",
    "efs",
    "eks",
    "elasticache",
    "elasticbeanstalk",
    "elasticloadbalancing",
    "elasticloadbalancingv2",
    "elasticsearch",
    "emr",
    "emrcontainers",
    "emrserverless",
    "entityresolution",
    "events",
    "eventschemas",
    "evidently",
    "finspace",
    "fis",
    "fms",
    "forecast",
    "frauddetector",
    "fsx",
    "gamelift",
    "globalaccelerator",
    "glue",
    "grafana",
    "greengrass",
    "greengrassv2",
    "groundstation",
    "guardduty",
    "healthimaging",
    "healthlake",
    "iam",
    "identitystore",
    "imagebuilder",
    "inspector",
    "inspectorv2",
    "internetmonitor",
    "iot",
    "iot1click",
    "iotanalytics",
    "iotcoredeviceadvisor",
    "iotevents",
    "iotfleetwise",
    "iotsitewise",
    "iottwinmaker",
    "iotwireless",
    "ivs",
    "ivschat",
    "kafkaconnect",
    "kendra",
    "kendraranking",
    "kinesis",
    "kinesisanalytics",
    "kinesisanalyticsv2",
    "kinesisfirehose",
    "kinesisvideo",
    "kms",
    "lakeformation",
    "lambda_",
    "launchwizard",
    "lex",
    "licensemanager",
    "lightsail",
    "location",
    "logs",
    "lookoutequipment",
    "lookoutmetrics",
    "lookoutvision",
    "m2",
    "macie",
    "managedblockchain",
    "mediaconnect",
    "mediaconvert",
    "medialive",
    "mediapackage",
    "mediapackagev2",
    "mediastore",
    "mediatailor",
    "memorydb",
    "msk",
    "mwaa",
    "neptune",
    "neptunegraph",
    "networkfirewall",
    "networkmanager",
    "nimblestudio",
    "oam",
    "omics",
    "opensearchserverless",
    "opensearchservice",
    "opsworks",
    "opsworkscm",
    "organizations",
    "osis",
    "panorama",
    "paymentcryptography",
    "pcaconnectorad",
    "pcaconnectorscep",
    "personalize",
    "pinpoint",
    "pinpointemail",
    "pipes",
    "proton",
    "qldb",
    "quicksight",
    "ram",
    "rds",
    "redshift",
    "redshiftserverless",
    "refactorspaces",
    "rekognition",
    "resiliencehub",
    "resourceexplorer2",
    "resourcegroups",
    "robomaker",
    "rolesanywhere",
    "route53",
    "route53profiles",
    "route53recoverycontrol",
    "route53recoveryreadiness",
    "route53resolver",
    "rum",
    "s3",
    "s3express",
    "s3objectlambda",
    "s3outposts",
    "sagemaker",
    "scheduler",
    "secretsmanager",
    "securityhub",
    "securitylake",
    "serverless",
    "servicecatalog",
    "servicecatalogappregistry",
    "servicediscovery",
    "ses",
    "shield",
    "signer",
    "simspaceweaver",
    "sns",
    "sqs",
    "ssm",
    "ssmcontacts",
    "ssmincidents",
    "sso",
    "stepfunctions",
    "supportapp",
    "synthetics",
    "systemsmanagersap",
    "timestream",
    "transfer",
    "verifiedpermissions",
    "voiceid",
    "vpclattice",
    "waf",
    "wafregional",
    "wafv2",
    "wisdom",
    "workspaces",
    "workspacesthinclient",
    "workspacesweb",
    "xray",
]

# Build extra header lines that include core wetwire_aws imports
# These are needed because setup_params() and setup_resources() inject
# names dynamically, but the IDE can't see that from static analysis
_CORE_IMPORT_LINES = [
    "# Core exports injected by setup_params() and setup_resources()",
    "from wetwire_aws import (",
    "    wetwire_aws,",
    "    ref,",
    "    get_att,",
    "    CloudFormationTemplate,",
    "    Parameter,",
    "    Output,",
    "    Mapping,",
    "    TemplateCondition,",
    "    PolicyStatement,",
    "    DenyStatement,",
    "    PolicyDocument,",
    "    Ref,",
    "    Attr,",
    "    Sub,",
    "    Join,",
    "    Select,",
    "    If,",
    "    Equals,",
    "    And,",
    "    Or,",
    "    Not,",
    "    Base64,",
    "    GetAZs,",
    "    FindInMap,",
    "    Condition,",
    "    STRING,",
    "    NUMBER,",
    "    AWS_REGION,",
    "    AWS_ACCOUNT_ID,",
    "    AWS_STACK_NAME,",
    "    BOOL,",
    "    STRING_EQUALS,",
    "    ARN_LIKE,",
    "    IP_ADDRESS,",
    ")",
    "from wetwire_aws.resources import (",
    "    " + ",\n    ".join(AWS_SERVICE_MODULES[:30]) + ",",
    "    " + ",\n    ".join(AWS_SERVICE_MODULES[30:60]) + ",",
    "    " + ",\n    ".join(AWS_SERVICE_MODULES[60:90]) + ",",
    "    " + ",\n    ".join(AWS_SERVICE_MODULES[90:120]) + ",",
    "    " + ",\n    ".join(AWS_SERVICE_MODULES[120:150]) + ",",
    "    " + ",\n    ".join(AWS_SERVICE_MODULES[150:]) + ",",
    ")",
]

AWS_STUB_CONFIG = StubConfig(
    package_name="wetwire_aws",
    core_imports=AWS_CORE_EXPORTS + AWS_SERVICE_MODULES,
    expand_star_imports={
        "wetwire_aws": AWS_CORE_EXPORTS + AWS_SERVICE_MODULES,
    },
    extra_header_lines=_CORE_IMPORT_LINES,
)
