run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/lex00/wetwire-aws

issues:
  # Don't limit issues per linter
  max-issues-per-linter: 0
  max-same-issues: 0
  # Exclude generated directories using regex patterns
  exclude-files:
    - "resources/.*"
    - "examples/.*"
